services:
  gateway:
    image: gateway-service:latest  # Используем ваш логин на Docker Hub
    ports:
      - "8080:8080"  # Прокидываем порт только для Gateway
    networks:
      - gts-network
    depends_on:
      - eureka
    environment:
      - EUREKA_SERVER_URL=http://eureka:8761/eureka
      - DB_URL=jdbc:mysql://37.140.192.158:3306/u1328132_gts2
      - DB_USERNAME=u1328132_default
      - DB_PASSWORD=Xyj_8oQ0

  auth-service:
    image: auth-service:latest  # Используем ваш логин на Docker Hub
    networks:
      - gts-network  # Подключаем к сети gts-network
    depends_on:
      - eureka
    environment:
      - EUREKA_SERVER_URL=http://eureka:8761/eureka  # Передаем адрес Eureka как переменную окружения
      - DB_URL=jdbc:mysql://37.140.192.158:3306/u1328132_gts2
      - DB_USERNAME=u1328132_default
      - DB_PASSWORD=Xyj_8oQ0

  eureka:
    image: eureka-service:latest  # Используем ваш логин на Docker Hub
    networks:
      - gts-network  # Подключаем к сети gts-network
    ports:
      - "8761:8761"  # Прокидываем порт для Eureka

  work-service:
    image: work-service:latest  # Используем ваш логин на Docker Hub
    depends_on:
      - auth-service  # Зависит от auth-service
      - eureka
    networks:
      - gts-network  # Подключаем к той же сети gts-network
    environment:
      - EUREKA_SERVER_URL=http://eureka:8761/eureka  # Передаем адрес Eureka как переменную окружения
      - DB_URL=jdbc:mysql://37.140.192.158:3306/u1328132_gts2
      - DB_USERNAME=u1328132_default
      - DB_PASSWORD=Xyj_8oQ0

networks:
  gts-network:
    driver: bridge  # Указываем, что сеть будет bridge
